Repository mobi/goponents, pull requests merged in 2019-08, with the labels that each got.

#108 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: enhancement

#110 GoTable always emits tableChange event, even in client mode.
  projects/go-lib/src/lib/components/go-table/go-table.component.ts
Labels: work in progress

#112 Updates README
  README.md
  package.json
Labels: enhancement, help wanted

#111 Adds contribution guide
  CONTRIBUTING.md
  README.md
Labels: enhancement, help wanted

#114 Update feature request template to be better suited to our needs
  .github/ISSUE_TEMPLATE/--feature-request.md
Labels: chore

#123 Update issue templates
  .github/ISSUE_TEMPLATE/--chore-or-maintenance-request.md
  .github/ISSUE_TEMPLATE/--feature-request.md
Labels: chore

#128 Go Input Component
  projects/go-lib/src/lib/components/go-input/go-input.component.html
  projects/go-lib/src/lib/components/go-input/go-input.component.spec.ts
  projects/go-lib/src/lib/components/go-input/go-input.component.ts
  projects/go-lib/src/lib/components/go-input/go-input.module.ts
  projects/go-lib/src/lib/go-shared.module.ts
  projects/go-lib/src/public_api.ts
  projects/go-tester/src/app/app-routing.module.ts
  projects/go-tester/src/app/app.component.ts
  projects/go-tester/src/app/app.module.ts
  projects/go-tester/src/app/components/test-page-3/test-page-3.component.html
  projects/go-tester/src/app/components/test-page-3/test-page-3.component.ts
Labels: feature

#131 Go Textarea Component
  projects/go-lib/src/lib/components/go-text-area/go-text-area.component.html
  projects/go-lib/src/lib/components/go-text-area/go-text-area.component.spec.ts
  projects/go-lib/src/lib/components/go-text-area/go-text-area.component.ts
  projects/go-lib/src/lib/components/go-text-area/go-text-area.module.ts
  projects/go-lib/src/lib/go-shared.module.ts
  projects/go-lib/src/public_api.ts
  projects/go-tester/src/app/app.module.ts
  projects/go-tester/src/app/components/test-page-3/test-page-3.component.html
  projects/go-tester/src/app/components/test-page-3/test-page-3.component.ts
Labels: feature

#129 Refactor accordion component
  package-lock.json
  package.json
  projects/go-lib/src/lib/animations/accordion.animation.ts
  projects/go-lib/src/lib/components/go-accordion/go-accordion-panel.component.html
  projects/go-lib/src/lib/components/go-accordion/go-accordion-panel.component.scss
  projects/go-lib/src/lib/components/go-accordion/go-accordion-panel.component.spec.ts
  projects/go-lib/src/lib/components/go-accordion/go-accordion-panel.component.ts
  projects/go-lib/src/lib/components/go-accordion/go-accordion.component.html
  projects/go-lib/src/lib/components/go-accordion/go-accordion.component.scss
  projects/go-lib/src/lib/components/go-accordion/go-accordion.component.spec.ts
  projects/go-lib/src/lib/components/go-accordion/go-accordion.component.ts
  projects/go-lib/src/lib/components/go-accordion/go-accordion.module.ts
  projects/go-lib/src/lib/components/go-action-sheet/go-panel/go-panel.component.scss
  projects/go-tester/src/app/app.component.html
  projects/go-tester/src/app/app.component.ts
  projects/go-tester/src/app/app.module.ts
  projects/go-tester/src/app/components/off-canvas-test/off-canvas-test.component.html
  projects/go-tester/src/app/components/off-canvas-test/off-canvas-test.component.ts
  projects/go-tester/src/app/components/test-page-1/test-page-1.component.html
Labels: chore

#141 Switch Toggle Module
  projects/go-lib/src/lib/components/go-switch-toggle/go-switch-toggle.component.html
  projects/go-lib/src/lib/components/go-switch-toggle/go-switch-toggle.component.scss
  projects/go-lib/src/lib/components/go-switch-toggle/go-switch-toggle.component.spec.ts
  projects/go-lib/src/lib/components/go-switch-toggle/go-switch-toggle.component.ts
  projects/go-lib/src/lib/components/go-switch-toggle/go-switch-toggle.module.ts
  projects/go-lib/src/lib/go-shared.module.ts
  projects/go-lib/src/public_api.ts
  projects/go-tester/src/app/app.module.ts
  projects/go-tester/src/app/components/test-page-3/test-page-3.component.html
  projects/go-tester/src/app/components/test-page-3/test-page-3.component.ts
Labels: feature

#135 Go Checkbox Module
  projects/go-lib/src/lib/components/go-checkbox/go-checkbox-group.component.html
  projects/go-lib/src/lib/components/go-checkbox/go-checkbox-group.component.spec.ts
  projects/go-lib/src/lib/components/go-checkbox/go-checkbox-group.component.ts
  projects/go-lib/src/lib/components/go-checkbox/go-checkbox.component.html
  projects/go-lib/src/lib/components/go-checkbox/go-checkbox.component.spec.ts
  projects/go-lib/src/lib/components/go-checkbox/go-checkbox.component.ts
  projects/go-lib/src/lib/components/go-checkbox/go-checkbox.module.ts
  projects/go-lib/src/lib/go-shared.module.ts
  projects/go-lib/src/public_api.ts
  projects/go-tester/src/app/app.module.ts
  projects/go-tester/src/app/components/test-page-3/test-page-3.component.html
  projects/go-tester/src/app/components/test-page-3/test-page-3.component.ts
Labels: feature

#56 Go-Copy Button
  projects/go-lib/src/lib/components/go-copy/go-copy.component.html
  projects/go-lib/src/lib/components/go-copy/go-copy.component.scss
  projects/go-lib/src/lib/components/go-copy/go-copy.component.spec.ts
  projects/go-lib/src/lib/components/go-copy/go-copy.component.ts
  projects/go-lib/src/lib/components/go-copy/go-copy.module.ts
  projects/go-lib/src/lib/go-shared.module.ts
  projects/go-lib/src/public_api.ts
  projects/go-tester/src/app/app.module.ts
  projects/go-tester/src/app/components/test-page-2/test-page-2.component.html
Labels: feature

#136 Manually updates classes when state changes to increase performance
  projects/go-lib/src/lib/components/go-accordion/go-accordion-panel.component.html
  projects/go-lib/src/lib/components/go-accordion/go-accordion-panel.component.scss
  projects/go-lib/src/lib/components/go-accordion/go-accordion-panel.component.spec.ts
  projects/go-lib/src/lib/components/go-accordion/go-accordion-panel.component.ts
  projects/go-lib/src/lib/components/go-accordion/go-accordion.component.spec.ts
  projects/go-lib/src/lib/components/go-accordion/go-accordion.component.ts
  projects/go-tester/src/app/components/test-page-1/test-page-1.component.html
Labels: chore
