Repository mobi/goponents, pull requests merged in 2019-11, with the labels that each got.

#288 Update selected state background of table rows
  projects/go-lib/src/lib/components/go-table/go-table.component.html
  projects/go-lib/src/lib/components/go-table/go-table.component.scss
Labels: chore

#307 Update Karma Jasmine Version
  package-lock.json
  package.json
Labels: chore

#309 File Upload Files Undefined
  projects/go-lib/src/lib/components/go-file-upload/go-file-upload.component.html
  projects/go-lib/src/lib/components/go-file-upload/go-file-upload.component.spec.ts
  projects/go-lib/src/lib/components/go-file-upload/go-file-upload.component.ts
Labels: bug

#291 Update checkbox design
  projects/go-lib/src/lib/components/go-checkbox/go-checkbox.component.html
  projects/go-lib/src/lib/components/go-checkbox/go-checkbox.component.ts
  projects/go-lib/src/styles/_forms.scss
  projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/checkbox-docs/checkbox-docs.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/checkbox-docs/checkbox-docs.component.ts
  projects/go-tester/src/app/components/test-page-3/test-page-3.component.html
  projects/go-tester/src/app/components/test-page-3/test-page-3.component.ts
Labels: chore

#287 Add row striping to go-table
  projects/go-lib/src/lib/components/go-table/go-table.component.scss
Labels: chore

#306 Pause Toaster On Hover
  projects/go-lib/src/lib/components/go-toast/go-toast.component.ts
  projects/go-lib/src/lib/components/go-toaster/go-toaster.component.html
  projects/go-lib/src/lib/components/go-toaster/go-toaster.component.ts
  projects/go-lib/src/lib/components/go-toaster/go-toaster.service.spec.ts
  projects/go-lib/src/lib/components/go-toaster/go-toaster.service.ts
  projects/go-style-guide/src/app/features/ui-kit/components/toast-docs/toast-docs.component.html
Labels: feature

#286 Table Row Details
  projects/go-lib/src/lib/animations/table-details.animation.ts
  projects/go-lib/src/lib/components/go-table/go-table.component.html
  projects/go-lib/src/lib/components/go-table/go-table.component.scss
  projects/go-lib/src/lib/components/go-table/go-table.component.spec.ts
  projects/go-lib/src/lib/components/go-table/go-table.component.ts
  projects/go-lib/src/lib/components/go-table/go-table.module.ts
  projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-details/table-details-test.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-details/table-details-test.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-details/table-details.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-details/table-details.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/table-docs/table-docs.component.ts
  projects/go-style-guide/src/app/features/ui-kit/routes/ui-kit-routing.module.ts
  projects/go-style-guide/src/app/features/ui-kit/ui-kit.module.ts
Labels: feature

#320 [Bugfix] Sidenav Active Indicator not working properly
  projects/go-lib/src/lib/components/go-side-nav/go-side-nav/go-side-nav.component.ts
  projects/go-lib/src/lib/components/go-side-nav/go-side-nav/go-side-nav.service.ts
  projects/go-tester/src/app/app-routing.module.ts
  projects/go-tester/src/app/app.component.html
  projects/go-tester/src/app/app.component.ts
  projects/go-tester/src/app/app.module.ts
  projects/go-tester/src/app/components/layout/layout.component.html
  projects/go-tester/src/app/components/layout/layout.component.ts
  projects/go-tester/src/app/components/test-page-4/test-page-4.component.html
Labels: bug

#304 Accordion Expression Changed After Checked
  projects/go-lib/src/lib/components/go-accordion/go-accordion-panel.component.ts
  projects/go-lib/src/lib/components/go-accordion/go-accordion.component.ts
Labels: bug

#318 Add Page Numbers to Pagination
  projects/go-lib/src/lib/components/go-table/go-table-page.model.ts
  projects/go-lib/src/lib/components/go-table/go-table.component.html
  projects/go-lib/src/lib/components/go-table/go-table.component.scss
  projects/go-lib/src/lib/components/go-table/go-table.component.spec.ts
  projects/go-lib/src/lib/components/go-table/go-table.component.ts
Labels: feature
