Repository mobi/goponents, pull requests merged in 2019-09, with the labels that each got.

#150 Add sass-lint
  .sass-lint.yml
  package-lock.json
  package.json
Labels: chore

#169 Fixes issue with tester accordion implementation
  projects/go-tester/src/app/components/test-page-2/test-page-2.component.html
Labels: bug

#151 Datepicker
  projects/go-lib/src/lib/components/go-datepicker/calendar-cell.model.ts
  projects/go-lib/src/lib/components/go-datepicker/calendar-views.scss
  projects/go-lib/src/lib/components/go-datepicker/date-adapter.ts
  projects/go-lib/src/lib/components/go-datepicker/day-view/go-calendar-day-view.component.html
  projects/go-lib/src/lib/components/go-datepicker/day-view/go-calendar-day-view.component.spec.ts
  projects/go-lib/src/lib/components/go-datepicker/day-view/go-calendar-day-view.component.ts
  projects/go-lib/src/lib/components/go-datepicker/go-calendar.component.html
  projects/go-lib/src/lib/components/go-datepicker/go-calendar.component.scss
  projects/go-lib/src/lib/components/go-datepicker/go-calendar.component.spec.ts
  projects/go-lib/src/lib/components/go-datepicker/go-calendar.component.ts
  projects/go-lib/src/lib/components/go-datepicker/go-calendar.ts
  projects/go-lib/src/lib/components/go-datepicker/go-datepicker.component.html
  projects/go-lib/src/lib/components/go-datepicker/go-datepicker.component.scss
  projects/go-lib/src/lib/components/go-datepicker/go-datepicker.component.spec.ts
  projects/go-lib/src/lib/components/go-datepicker/go-datepicker.component.ts
  projects/go-lib/src/lib/components/go-datepicker/go-datepicker.module.ts
  projects/go-lib/src/lib/components/go-datepicker/locale-format.ts
  projects/go-lib/src/lib/components/go-datepicker/month-view/go-calendar-month-view.component.html
  projects/go-lib/src/lib/components/go-datepicker/month-view/go-calendar-month-view.component.spec.ts
  projects/go-lib/src/lib/components/go-datepicker/month-view/go-calendar-month-view.component.ts
  projects/go-lib/src/lib/components/go-datepicker/year-view/go-calendar-year-view.component.html
  projects/go-lib/src/lib/components/go-datepicker/year-view/go-calendar-year-view.component.spec.ts
  projects/go-lib/src/lib/components/go-datepicker/year-view/go-calendar-year-view.component.ts
  projects/go-lib/src/lib/go-shared.module.ts
  projects/go-lib/src/public_api.ts
  projects/go-tester/src/app/app.module.ts
  projects/go-tester/src/app/components/test-page-3/test-page-3.component.html
  projects/go-tester/src/app/components/test-page-3/test-page-3.component.ts
Labels: feature

#181 Fix horizontal overflow in off-canvas window. Closes #178
  projects/go-lib/src/lib/components/go-off-canvas/go-off-canvas.component.scss
Labels: bug

#190 Fixes go select missing bind value
  projects/go-lib/src/lib/components/go-select/go-select.component.html
  projects/go-tester/src/app/components/test-page-3/test-page-3.component.html
  projects/go-tester/src/app/components/test-page-3/test-page-3.component.ts
Labels: bug

#165 Add grid modifiers for justify content
  projects/go-lib/src/styles/_grid.scss
Labels: chore

#188 [Bug] Table Page Item Count
  projects/go-lib/src/lib/components/go-table/go-table.component.spec.ts
  projects/go-lib/src/lib/components/go-table/go-table.component.ts
Labels: bug

#199 [Bug] Fixed Toast Heading Styles
  projects/go-lib/src/lib/components/go-toast/go-toast.component.html
Labels: bug

#198 [Chore] Added light and dark options to loader
  projects/go-lib/src/lib/components/go-loader/go-loader.component.scss
  projects/go-lib/src/lib/components/go-loader/go-loader.component.ts
Labels: chore

#201 [Chore] Adjust Menu Icon Size
  projects/go-lib/src/lib/components/go-header/go-header.component.html
  projects/go-lib/src/lib/components/go-icon-button/go-icon-button.component.html
  projects/go-lib/src/lib/components/go-icon-button/go-icon-button.component.scss
  projects/go-lib/src/lib/components/go-icon-button/go-icon-button.component.ts
Labels: chore

#200 [Bug] Side Nav Doesn't Scroll
  projects/go-lib/src/lib/components/go-header/go-header.component.scss
  projects/go-lib/src/lib/components/go-layout/go-layout.component.scss
  projects/go-lib/src/styles/_variables.scss
Labels: bug

#196 Adjusted height of indicator in nav
  projects/go-lib/src/lib/components/go-side-nav/go-nav-item/go-nav-item.component.scss
  projects/go-tester/src/app/app-routing.module.ts
  projects/go-tester/src/app/app.component.ts
  projects/go-tester/src/app/app.module.ts
  projects/go-tester/src/app/components/test-page-4/test-page-4.component.html
  projects/go-tester/src/app/components/test-page-4/test-page-4.component.ts
Labels: chore
