Repository mobi/goponents, pull requests merged in 2019-10, with the labels that each got.

#247 Add go-select documentation
  projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/select-docs/select-docs.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/select-docs/select-docs.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/form-docs/form-docs.component.ts
  projects/go-style-guide/src/app/features/ui-kit/routes/ui-kit-routing.module.ts
  projects/go-style-guide/src/app/features/ui-kit/ui-kit.module.ts
Labels: documentation

#251 Add Placeholder Binding to GoSelect Component
  projects/go-lib/src/lib/components/go-select/go-select.component.html
  projects/go-lib/src/lib/components/go-select/go-select.component.ts
  projects/go-tester/src/app/components/test-page-3/test-page-3.component.html
Labels: chore

#254 [Chore] Update Contribution and PR Template
  CONTRIBUTING.md
  PULL_REQUEST_TEMPLATE
Labels: chore

#167 Ability to Brand Side Nav and Accordion
  projects/go-lib/src/lib/components/go-accordion/go-accordion-panel.component.html
  projects/go-lib/src/lib/components/go-accordion/go-accordion-panel.component.scss
  projects/go-lib/src/lib/components/go-accordion/go-accordion-panel.component.spec.ts
  projects/go-lib/src/lib/components/go-accordion/go-accordion-panel.component.ts
  projects/go-lib/src/lib/components/go-accordion/go-accordion.component.spec.ts
  projects/go-lib/src/lib/components/go-accordion/go-accordion.module.ts
  projects/go-lib/src/lib/components/go-side-nav/go-nav-item/go-nav-item.component.html
  projects/go-lib/src/lib/components/go-side-nav/go-nav-item/go-nav-item.component.scss
  projects/go-lib/src/lib/components/go-side-nav/go-nav-item/go-nav-item.component.ts
  projects/go-lib/src/lib/components/go-side-nav/go-side-nav.module.ts
  projects/go-lib/src/lib/go-config.model.ts
  projects/go-lib/src/lib/go-config.service.ts
  projects/go-lib/src/public_api.ts
  projects/go-style-guide/src/app/app.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/configuration-docs/configuration-docs.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/configuration-docs/configuration-docs.component.ts
  projects/go-style-guide/src/app/features/ui-kit/routes/ui-kit-routing.module.ts
  projects/go-style-guide/src/app/features/ui-kit/ui-kit.module.ts
  projects/go-tester/src/app/app.component.ts
Labels: feature

#259 [Chore] Action Sheet Documentation
  projects/go-lib/src/lib/components/go-action-sheet/go-action-sheet.component.scss
  projects/go-style-guide/src/app/app.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/action-sheet-docs/action-sheet-docs.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/action-sheet-docs/action-sheet-docs.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/action-sheet-docs/components/action-sheet-overview/action-sheet-overview.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/action-sheet-docs/components/action-sheet-overview/action-sheet-overview.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/action-sheet-docs/components/action-sheet-panel-docs/action-sheet-panel-docs.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/action-sheet-docs/components/action-sheet-panel-docs/action-sheet-panel-docs.component.ts
  projects/go-style-guide/src/app/features/ui-kit/routes/ui-kit-routing.module.ts
  projects/go-style-guide/src/app/features/ui-kit/ui-kit.module.ts
Labels: chore, documentation

#258 Add loading input to go-select
  projects/go-lib/src/lib/components/go-select/go-select.component.html
  projects/go-lib/src/lib/components/go-select/go-select.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/select-docs/select-docs.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/select-docs/select-docs.component.ts
  projects/go-tester/src/app/components/test-page-3/test-page-3.component.html
  projects/go-tester/src/app/components/test-page-3/test-page-3.component.ts
Labels: chore

#210 Table Column Sorting
  projects/go-lib/src/lib/components/go-table/go-table-column.component.ts
  projects/go-lib/src/lib/components/go-table/go-table.component.html
  projects/go-lib/src/lib/components/go-table/go-table.component.scss
  projects/go-lib/src/lib/components/go-table/go-table.component.spec.ts
  projects/go-lib/src/lib/components/go-table/go-table.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-sorting/table-sorting.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-sorting/table-sorting.component.ts
  projects/go-tester/src/app/components/test-page-1/test-page-1.component.html
  projects/go-tester/src/app/components/test-page-1/test-page-1.component.ts
Labels: feature

#243 Switch toggle label position
  projects/go-lib/src/lib/components/go-switch-toggle/go-switch-toggle.component.html
  projects/go-lib/src/lib/components/go-switch-toggle/go-switch-toggle.component.scss
  projects/go-lib/src/lib/components/go-switch-toggle/go-switch-toggle.component.ts
  projects/go-tester/src/app/components/test-page-3/test-page-3.component.html
  projects/go-tester/src/app/components/test-page-3/test-page-3.component.ts
Labels: chore

#273 [Chore] 5 Column Documentation
  projects/go-style-guide/src/app/features/standards/components/grid/grid.component.html
  projects/go-style-guide/src/app/features/standards/components/grid/grid.component.ts
Labels: documentation

#270 Chore z index for load screen
  projects/go-lib/src/lib/components/go-layout/go-layout.component.scss
  projects/go-lib/src/styles/_mixins.scss
Labels: chore

#267 BUG: fix go-select dropdowns being cut off in go-accordian-panels
  projects/go-lib/src/lib/animations/accordion.animation.ts
  projects/go-lib/src/lib/components/go-accordion/go-accordion-panel.component.scss
  projects/go-tester/src/app/components/off-canvas-test/off-canvas-test.component.html
  projects/go-tester/src/app/components/off-canvas-test/off-canvas-test.component.ts
Labels: bug

#274 [Chore] Theme & Slim Accordion Documentation
  projects/go-style-guide/src/app/app.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/accordion-docs/accordion-docs.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/accordion-docs/accordion-docs.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/accordion-docs/components/accordion-overview/accordion-overview.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/accordion-docs/components/accordion-overview/accordion-overview.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/accordion-docs/components/accordion-panel-docs/accordion-panel-docs.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/accordion-docs/components/accordion-panel-docs/accordion-panel-docs.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/accordion-panel-docs/accordion-panel-docs.component.spec.ts
  projects/go-style-guide/src/app/features/ui-kit/components/action-sheet-docs/components/action-sheet-overview/action-sheet-overview.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/action-sheet-docs/components/action-sheet-overview/action-sheet-overview.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/action-sheet-docs/components/action-sheet-panel-docs/action-sheet-panel-docs.component.ts
  projects/go-style-guide/src/app/features/ui-kit/routes/ui-kit-routing.module.ts
  projects/go-style-guide/src/app/features/ui-kit/ui-kit.module.ts
  projects/go-style-guide/src/styles/_typography.scss
Labels: documentation

#271 [Chore] Button Design Update
  projects/go-lib/src/lib/components/go-button/go-button.component.html
  projects/go-lib/src/lib/components/go-button/go-button.component.scss
  projects/go-lib/src/lib/components/go-button/go-button.component.spec.ts
  projects/go-lib/src/lib/components/go-button/go-button.component.ts
  projects/go-lib/src/lib/components/go-button/go-button.module.ts
  projects/go-lib/src/lib/components/go-icon/go-icon.component.scss
  projects/go-lib/src/lib/components/go-loader/go-loader.component.scss
  projects/go-lib/src/lib/components/go-loader/go-loader.component.spec.ts
  projects/go-lib/src/lib/components/go-loader/go-loader.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/button-docs/button-docs.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/button-docs/button-docs.component.ts
Labels: chore

#268 Icon Button Documentation
  projects/go-style-guide/src/app/app.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/icon-button-docs/icon-button-docs.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/icon-button-docs/icon-button-docs.component.spec.ts
  projects/go-style-guide/src/app/features/ui-kit/components/icon-button-docs/icon-button-docs.component.ts
  projects/go-style-guide/src/app/features/ui-kit/routes/ui-kit-routing.module.ts
  projects/go-style-guide/src/app/features/ui-kit/ui-kit.module.ts
Labels: documentation

#260 Add appendTo input to go-select
  projects/go-lib/src/lib/components/go-select/go-select.component.html
  projects/go-lib/src/lib/components/go-select/go-select.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/select-docs/select-docs.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/select-docs/select-docs.component.ts
  projects/go-style-guide/src/app/features/ui-kit/ui-kit.module.ts
  projects/go-tester/src/app/app.component.ts
  projects/go-tester/src/app/app.module.ts
Labels: chore

#272 [Chore] Loader Type Docs
  projects/go-style-guide/src/app/features/ui-kit/components/loader-docs/loader-docs.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/loader-docs/loader-docs.component.ts
Labels: documentation

#276 [Chore] Removed Gosheets References from Documentation
  projects/go-style-guide/src/app/features/dashboard/components/getting-started/getting-started.component.html
  projects/go-style-guide/src/app/features/dashboard/components/getting-started/getting-started.component.spec.ts
  projects/go-style-guide/src/app/features/dashboard/components/getting-started/getting-started.component.ts
  projects/go-style-guide/src/app/features/standards/components/colors/colors.component.html
Labels: documentation

#278 [Chore] Switch Toggle Documentation
  projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/datepicker-docs/datepicker-docs.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/input-docs/input-docs.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/select-docs/select-docs.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/switch-toggle-docs/switch-toggle-docs.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/switch-toggle-docs/switch-toggle-docs.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/text-area-docs/text-area-docs.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/form-docs/form-docs.component.ts
  projects/go-style-guide/src/app/features/ui-kit/routes/ui-kit-routing.module.ts
  projects/go-style-guide/src/app/features/ui-kit/ui-kit.module.ts
Labels: documentation

#279 [Chore] Radio Button Documentation
  projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/radio-button-docs/radio-button-docs.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/radio-button-docs/radio-button-docs.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/form-docs/form-docs.component.ts
  projects/go-style-guide/src/app/features/ui-kit/routes/ui-kit-routing.module.ts
  projects/go-style-guide/src/app/features/ui-kit/ui-kit.module.ts
Labels: documentation

#283 [Chore] Checkbox Documentation
  projects/go-lib/src/lib/components/go-checkbox/go-checkbox.component.html
  projects/go-lib/src/lib/components/go-checkbox/go-checkbox.component.spec.ts
  projects/go-style-guide/src/app/features/ui-kit/components/button-docs/button-docs.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/checkbox-docs/checkbox-docs.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/checkbox-docs/checkbox-docs.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/form-docs/form-docs.component.ts
  projects/go-style-guide/src/app/features/ui-kit/routes/ui-kit-routing.module.ts
  projects/go-style-guide/src/app/features/ui-kit/ui-kit.module.ts
Labels: documentation

#281 Add ability to brand top left header
  projects/go-lib/src/lib/components/go-button/go-button.component.html
  projects/go-lib/src/lib/components/go-header/go-header.component.html
  projects/go-lib/src/lib/components/go-header/go-header.component.scss
  projects/go-lib/src/lib/components/go-header/go-header.component.spec.ts
  projects/go-lib/src/lib/components/go-header/go-header.component.ts
  projects/go-lib/src/lib/components/go-icon-button/go-icon-button.component.scss
  projects/go-lib/src/lib/go-config.model.ts
  projects/go-lib/src/lib/go-config.service.spec.ts
  projects/go-lib/src/lib/go-config.service.ts
  projects/go-style-guide/src/app/features/ui-kit/components/configuration-docs/configuration-docs.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/configuration-docs/configuration-docs.component.ts
  projects/go-tester/src/app/app.component.html
  projects/go-tester/src/app/app.component.ts
  projects/go-tester/src/app/components/test-page-2/test-page-2.component.html
  projects/go-tester/src/app/components/test-page-2/test-page-2.component.ts
Labels: feature

#209 Go-Footer
  projects/go-lib/src/lib/components/go-copy/go-copy.component.html
  projects/go-lib/src/lib/components/go-copy/go-copy.component.scss
  projects/go-lib/src/lib/components/go-footer/go-footer.component.html
  projects/go-lib/src/lib/components/go-footer/go-footer.component.scss
  projects/go-lib/src/lib/components/go-footer/go-footer.component.spec.ts
  projects/go-lib/src/lib/components/go-footer/go-footer.component.ts
  projects/go-lib/src/lib/components/go-footer/go-footer.module.ts
  projects/go-lib/src/lib/components/go-layout/go-layout.component.html
  projects/go-lib/src/lib/components/go-layout/go-layout.component.scss
  projects/go-lib/src/lib/go-shared.module.ts
  projects/go-lib/src/public_api.ts
  projects/go-style-guide/src/app/app.component.html
  projects/go-style-guide/src/app/app.component.ts
  projects/go-style-guide/src/app/app.module.ts
  projects/go-style-guide/src/app/features/ui-kit/components/layout-docs/components/layout-example/layout-example.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/layout-docs/components/layout-footer/layout-footer.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/layout-docs/components/layout-footer/layout-footer.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/layout-docs/layout-docs.component.ts
  projects/go-style-guide/src/app/features/ui-kit/routes/ui-kit-routing.module.ts
  projects/go-style-guide/src/app/features/ui-kit/ui-kit.module.ts
  projects/go-style-guide/src/app/shared/components/sub-nav/sub-nav.component.scss
  projects/go-tester/src/app/app.component.html
  projects/go-tester/src/app/app.module.ts
Labels: feature

#149 Go File Upload
  projects/go-lib/src/lib/components/go-file-upload/go-dragon-drop.directive.ts
  projects/go-lib/src/lib/components/go-file-upload/go-file-upload.component.html
  projects/go-lib/src/lib/components/go-file-upload/go-file-upload.component.scss
  projects/go-lib/src/lib/components/go-file-upload/go-file-upload.component.spec.ts
  projects/go-lib/src/lib/components/go-file-upload/go-file-upload.component.ts
  projects/go-lib/src/lib/components/go-file-upload/go-file-upload.module.ts
  projects/go-lib/src/lib/go-shared.module.ts
  projects/go-lib/src/public_api.ts
  projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/file-upload-docs/file-upload-docs.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/file-upload-docs/file-upload-docs.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/form-docs/form-docs.component.ts
  projects/go-style-guide/src/app/features/ui-kit/routes/ui-kit-routing.module.ts
  projects/go-style-guide/src/app/features/ui-kit/ui-kit.module.ts
  projects/go-tester/src/app/app.module.ts
  projects/go-tester/src/app/components/test-page-3/test-page-3.component.html
  projects/go-tester/src/app/components/test-page-3/test-page-3.component.ts
Labels: feature

#284 Go Select Async Items
  projects/go-lib/src/lib/components/go-select/go-select.component.html
  projects/go-lib/src/lib/components/go-select/go-select.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/select-docs/select-docs.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/select-docs/select-docs.component.ts
Labels: feature
