Repository mobi/goponents, pull requests merged in 2020-02, with the labels that each got.

#431 Add Visual Disabled State to GoIconButton
  projects/go-lib/src/lib/components/go-icon-button/go-icon-button.component.html
  projects/go-lib/src/lib/components/go-icon-button/go-icon-button.component.scss
Labels: chore

#433 Update go-icon iconModifier documentation
  projects/go-lib/src/lib/components/go-icon/go-icon.component.scss
  projects/go-style-guide/src/app/features/ui-kit/components/icon-docs/icon-docs.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/icon-docs/icon-docs.component.ts
Labels: documentation

#438 Fix GoIconButton Hover Background
  projects/go-lib/src/lib/components/go-icon-button/go-icon-button.component.scss
Labels: chore

#440 Add Select All button to GoSelect
  projects/go-lib/src/lib/components/go-select/go-select.component.html
  projects/go-lib/src/lib/components/go-select/go-select.component.spec.ts
  projects/go-lib/src/lib/components/go-select/go-select.component.ts
  projects/go-lib/src/lib/components/go-select/go-select.module.ts
Labels: feature

#454 Add Unit Tests For GoModalService
  projects/go-lib/src/lib/components/go-modal/go-modal.service.spec.ts
  projects/go-lib/src/lib/components/go-modal/go-modal.service.ts
Labels: chore

#469 [Feature] App drawer support within side navigation
  projects/go-lib/src/lib/components/go-action-sheet/go-action-sheet.component.scss
  projects/go-lib/src/lib/components/go-action-sheet/go-action-sheet.component.ts
  projects/go-lib/src/lib/components/go-action-sheet/go-panel/go-panel.component.html
  projects/go-lib/src/lib/components/go-side-nav/go-side-nav.module.ts
  projects/go-lib/src/lib/components/go-side-nav/go-side-nav/go-side-nav.component.html
  projects/go-lib/src/lib/components/go-side-nav/go-side-nav/go-side-nav.component.scss
  projects/go-lib/src/lib/components/go-side-nav/go-side-nav/go-side-nav.component.spec.ts
  projects/go-lib/src/lib/components/go-side-nav/go-side-nav/go-side-nav.component.ts
  projects/go-lib/src/lib/components/go-side-nav/nav-app-drawer.model.ts
  projects/go-lib/src/public_api.ts
  projects/go-style-guide/src/app/app.component.html
  projects/go-style-guide/src/app/app.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/action-sheet-docs/components/action-sheet-overview/action-sheet-overview.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/action-sheet-docs/components/action-sheet-overview/action-sheet-overview.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/action-sheet-docs/components/action-sheet-panel-docs/action-sheet-panel-docs.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/layout-docs/components/layout-app-drawer/layout-app-drawer.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/layout-docs/components/layout-app-drawer/layout-app-drawer.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/layout-docs/components/layout-nav/layout-nav.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/layout-docs/components/layout-nav/layout-nav.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/layout-docs/layout-docs.component.ts
  projects/go-style-guide/src/app/features/ui-kit/routes/ui-kit-routing.module.ts
  projects/go-style-guide/src/app/features/ui-kit/ui-kit.module.ts
Labels: feature

#465 Add go-off-canvas unit tests
  projects/go-lib/src/lib/components/go-off-canvas/go-off-canvas-service.spec.ts
  projects/go-lib/src/lib/components/go-off-canvas/go-off-canvas.component.spec.ts
  projects/go-lib/src/lib/components/go-off-canvas/go-off-canvas.service.ts
Labels: chore
