Repository mobi/goponents, pull requests merged in 2020-12, with the labels that each got.

#706 Text Area Max Length
  projects/go-lib/src/lib/components/go-text-area/go-text-area.component.html
  projects/go-lib/src/lib/components/go-text-area/go-text-area.component.spec.ts
  projects/go-lib/src/lib/components/go-text-area/go-text-area.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/text-area-docs/text-area-docs.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/text-area-docs/text-area-docs.component.ts
Labels: feature, hacktoberfest-accepted

#724 [Bug] Table: Duplicate selectAllEvents fired
  projects/go-lib/src/lib/components/go-table/go-table.component.ts
Labels: bug

#723 [Chore] Modal & Off Canvas Type Improvements
  projects/go-lib/src/lib/components/go-modal/go-modal-options.ts
  projects/go-lib/src/lib/components/go-modal/go-modal.component.spec.ts
  projects/go-lib/src/lib/components/go-modal/go-modal.component.ts
  projects/go-lib/src/lib/components/go-modal/go-modal.item.ts
  projects/go-lib/src/lib/components/go-modal/go-modal.service.spec.ts
  projects/go-lib/src/lib/components/go-modal/go-modal.service.ts
  projects/go-lib/src/lib/components/go-off-canvas/go-off-canvas-options.ts
  projects/go-lib/src/lib/components/go-off-canvas/go-off-canvas-service.spec.ts
  projects/go-lib/src/lib/components/go-off-canvas/go-off-canvas.component.ts
  projects/go-lib/src/lib/components/go-off-canvas/go-off-canvas.interface.ts
  projects/go-lib/src/lib/components/go-off-canvas/go-off-canvas.service.ts
  projects/go-lib/src/public_api.ts
  projects/go-style-guide/src/app/features/ui-kit/components/modal-docs/modal-docs.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/modal-docs/modal-docs.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/off-canvas-docs/off-canvas-docs.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/off-canvas-docs/off-canvas-docs.component.ts
Labels: chore
