Repository mobi/goponents, pull requests merged in 2020-05, with the labels that each got.

#544 Update Style Guide To Represent Ideal Template Formatting
  projects/go-style-guide/src/app/features/standards/components/forms/forms.component.html
  projects/go-style-guide/src/app/features/standards/components/forms/forms.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/button-docs/button-docs.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/configuration-docs/configuration-docs.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/configuration-docs/configuration-docs.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/checkbox-docs/checkbox-docs.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/checkbox-docs/checkbox-docs.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/datepicker-docs/datepicker-docs.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/datepicker-docs/datepicker-docs.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/file-upload-docs/file-upload-docs.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/file-upload-docs/file-upload-docs.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/input-docs/input-docs.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/input-docs/input-docs.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/radio-button-docs/radio-button-docs.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/radio-button-docs/radio-button-docs.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/select-docs/select-docs.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/switch-toggle-docs/switch-toggle-docs.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/switch-toggle-docs/switch-toggle-docs.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/text-area-docs/text-area-docs.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/text-area-docs/text-area-docs.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/header-bar-docs/header-bar-docs.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/icon-button-docs/icon-button-docs.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/icon-button-docs/icon-button-docs.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/off-canvas-docs/off-canvas-docs.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/off-canvas-docs/off-canvas-docs.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/server-integration/server-integration.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-actions-docs/table-actions-docs.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-actions-docs/table-actions-docs.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-details/table-details.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-details/table-details.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-filters/table-filters.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-searching/table-searching.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-selection/table-selection.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-selection/table-selection.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/toast-docs/toast-docs.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/toast-docs/toast-docs.component.ts
Labels: chore

#545 Add classes for horizontal rules within go-cards
  projects/go-lib/src/styles/_globals.scss
  projects/go-style-guide/src/app/features/ui-kit/components/card-docs/card-docs.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/card-docs/card-docs.component.ts
Labels: feature

#536 BUGFIX: Go Off Canvas Header Color in Mobile
  projects/go-lib/src/lib/components/go-off-canvas/go-off-canvas.component.scss
Labels: bug

#547 Update dark theme colors
  projects/go-lib/src/lib/components/go-off-canvas/go-off-canvas.component.scss
  projects/go-lib/src/lib/components/go-side-nav/go-side-nav/go-side-nav.component.scss
  projects/go-lib/src/styles/_forms.scss
  projects/go-lib/src/styles/_variables.scss
Labels: chore
