Repository mobi/goponents, pull requests merged in 2020-10, with the labels that each got.

#683 [Chore] Base Color
  projects/go-lib/src/styles/_typography.scss
Labels: hacktoberfest-accepted

#670 Update go-checkbox background color and integrate into go-table
  projects/go-lib/src/lib/components/go-checkbox/go-checkbox.component.html
  projects/go-lib/src/lib/components/go-checkbox/go-checkbox.component.spec.ts
  projects/go-lib/src/lib/components/go-checkbox/go-checkbox.component.ts
  projects/go-lib/src/lib/components/go-table/go-table.component.html
  projects/go-lib/src/lib/components/go-table/go-table.component.scss
  projects/go-lib/src/lib/components/go-table/go-table.component.spec.ts
  projects/go-lib/src/lib/components/go-table/go-table.component.ts
  projects/go-lib/src/lib/components/go-table/go-table.module.ts
  projects/go-lib/src/lib/directives/go-copy-card-link/go-copy-card-link.directive.spec.ts
  projects/go-lib/src/styles/_forms.scss
  projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/checkbox-docs/checkbox-docs.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/checkbox-docs/checkbox-docs.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-selection/table-selection.component.html
Labels: chore, hacktoberfest-accepted

#685 Add split-button functionality to go-button
  projects/go-lib/src/lib/components/go-button/go-button.component.html
  projects/go-lib/src/lib/components/go-button/go-button.component.scss
  projects/go-lib/src/lib/components/go-button/go-button.component.spec.ts
  projects/go-lib/src/lib/components/go-button/go-button.component.ts
  projects/go-lib/src/lib/components/go-button/go-split-button-option.model.ts
  projects/go-lib/src/public_api.ts
  projects/go-style-guide/src/app/features/ui-kit/components/button-docs/button-docs.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/button-docs/button-docs.component.ts
Labels: feature, hacktoberfest-accepted

#697 Support for 'target' element in app drawer config
  projects/go-lib/src/lib/components/go-action-sheet/go-panel/go-panel.component.html
  projects/go-lib/src/lib/components/go-action-sheet/go-panel/go-panel.component.ts
  projects/go-lib/src/lib/components/go-side-nav/go-side-nav/go-side-nav.component.html
  projects/go-lib/src/lib/components/go-side-nav/nav-app-drawer.model.ts
  projects/go-style-guide/src/app/app.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/action-sheet-docs/components/action-sheet-panel-docs/action-sheet-panel-docs.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/action-sheet-docs/components/action-sheet-panel-docs/action-sheet-panel-docs.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/layout-docs/components/layout-app-drawer/layout-app-drawer.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/layout-docs/components/layout-app-drawer/layout-app-drawer.component.ts
Labels: hacktoberfest-accepted

#695 Updated docs for go-select disable mode
  projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/select-docs/select-docs.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/select-docs/select-docs.component.ts
Labels: hacktoberfest-accepted
