Repository mobi/goponents, pull requests merged in 2020-11, with the labels that each got.

#692 Emit rowSelectionEvent when selecting or deselecting all table rows
  projects/go-lib/src/lib/components/go-table/go-table.component.spec.ts
  projects/go-lib/src/lib/components/go-table/go-table.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-selection/table-selection.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-selection/table-selection.component.ts
Labels: chore, hacktoberfest-accepted

#704 Changes to Closing Modals
  projects/go-lib/src/lib/components/go-modal/go-modal.component.html
  projects/go-lib/src/lib/components/go-modal/go-modal.component.spec.ts
  projects/go-lib/src/lib/components/go-modal/go-modal.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/modal-docs/modal-docs.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/modal-docs/modal-docs.component.ts
Labels: feature, hacktoberfest-accepted

#687 Update Neutral Colors as per DSM (Issue #323)
  projects/go-lib/src/lib/components/go-hint/go-hint.component.scss
  projects/go-lib/src/lib/components/go-search/go-search.component.scss
  projects/go-lib/src/styles/_mixins.scss
Labels: hacktoberfest-accepted

#701 Add closeOnClick input to go-panel
  projects/go-lib/src/lib/components/go-action-sheet/go-panel/go-panel.component.html
  projects/go-lib/src/lib/components/go-action-sheet/go-panel/go-panel.component.spec.ts
  projects/go-lib/src/lib/components/go-action-sheet/go-panel/go-panel.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/action-sheet-docs/components/action-sheet-panel-docs/action-sheet-panel-docs.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/action-sheet-docs/components/action-sheet-panel-docs/action-sheet-panel-docs.component.ts
Labels: chore, hacktoberfest-accepted

#667 Side navigation tweaks 657
  projects/go-lib/src/lib/components/go-side-nav/go-nav-group/go-nav-group.component.scss
  projects/go-lib/src/lib/components/go-side-nav/go-side-nav.module.ts
  projects/go-lib/src/lib/components/go-side-nav/go-side-nav/go-side-nav.component.html
  projects/go-lib/src/lib/components/go-side-nav/go-side-nav/go-side-nav.component.scss
  projects/go-lib/src/lib/components/go-side-nav/go-side-nav/go-side-nav.component.spec.ts
Labels: hacktoberfest-accepted

#693 Unsubscribe in components to prevent memory leaks
  projects/go-lib/src/lib/components/go-accordion/go-accordion-panel.component.ts
  projects/go-lib/src/lib/components/go-accordion/go-accordion.component.ts
  projects/go-lib/src/lib/components/go-file-upload/go-file-upload.component.ts
  projects/go-lib/src/lib/components/go-layout/go-layout.component.ts
  projects/go-lib/src/lib/components/go-modal/go-modal.component.ts
  projects/go-lib/src/lib/components/go-off-canvas/go-off-canvas.component.ts
  projects/go-lib/src/lib/components/go-search/go-search.component.ts
  projects/go-lib/src/lib/components/go-side-nav/go-nav-group/go-nav-group.component.ts
  projects/go-lib/src/lib/components/go-side-nav/go-nav-item/go-nav-item.component.ts
  projects/go-lib/src/lib/components/go-side-nav/go-side-nav/go-side-nav.component.ts
  projects/go-lib/src/lib/components/go-table/go-table.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/configuration-docs/configuration-docs.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/header-bar-docs/header-bar-docs.component.ts
  projects/go-tester/src/app/components/search-test/search-test.component.ts
  projects/go-tester/src/app/components/test-page-1/test-page-1.component.ts
Labels: chore, hacktoberfest-accepted

#699 Max and min length bindings for goInput - 691
  projects/go-lib/src/lib/components/go-input/go-input.component.html
  projects/go-lib/src/lib/components/go-input/go-input.component.spec.ts
  projects/go-lib/src/lib/components/go-input/go-input.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/input-docs/input-docs.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/input-docs/input-docs.component.ts
Labels: hacktoberfest-accepted

#674 Dynamically Created Accordions Not Opening
  projects/go-lib/src/lib/components/go-accordion/go-accordion.component.spec.ts
  projects/go-lib/src/lib/components/go-accordion/go-accordion.component.ts
Labels: hacktoberfest-accepted

#698 Dark theme go select 676
  projects/go-lib/src/lib/components/go-select/go-select.component.html
  projects/go-lib/src/lib/components/go-select/go-select.component.scss
  projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/select-docs/select-docs.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/select-docs/select-docs.component.ts
Labels: hacktoberfest-accepted
