Repository mobi/goponents, pull requests merged in 2021-08, with the labels that each got.

#818 [Feature] Table Generic Typing
  projects/go-lib/src/lib/components/go-table/go-table-config.model.ts
  projects/go-lib/src/lib/components/go-table/go-table.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-overview/table-overview.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-overview/table-overview.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/table-docs/table-docs.service.ts
Labels: in progress, feature

#822 [Chore] go-button Secondary Colors
  projects/go-lib/src/lib/components/go-button/go-button.component.scss
Labels: chore

#819 [Feature] go-toast maxHeight & icon overrides
  projects/go-lib/src/lib/components/go-toast/go-toast.component.html
  projects/go-lib/src/lib/components/go-toast/go-toast.component.scss
  projects/go-lib/src/lib/components/go-toast/go-toast.component.spec.ts
  projects/go-lib/src/lib/components/go-toast/go-toast.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/toast-docs/toast-docs.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/toast-docs/toast-docs.component.ts
Labels: feature

#816 added remove all on select
  projects/go-lib/src/lib/components/go-select/go-select.component.html
  projects/go-lib/src/lib/components/go-select/go-select.component.spec.ts
  projects/go-lib/src/lib/components/go-select/go-select.component.ts
Labels: in progress, feature

#823 [Chore] Form Toggles Borders & Box Shadows
  projects/go-lib/src/lib/components/go-radio/go-radio-button.component.scss
  projects/go-lib/src/lib/components/go-switch-toggle/go-switch-toggle.component.scss
  projects/go-lib/styles/_forms.scss
Labels: chore

#821 [Bug] go-side-nav Active Indicator
  projects/go-lib/src/lib/components/go-side-nav/go-nav-group/go-nav-group.component.html
  projects/go-lib/src/lib/components/go-side-nav/go-nav-item/go-nav-item.component.scss
Labels: bug

#820 [Feature] go-table wrapContent
  projects/go-lib/src/lib/components/go-table/go-table-column.component.ts
  projects/go-lib/src/lib/components/go-table/go-table.component.html
  projects/go-lib/src/lib/components/go-table/go-table.component.scss
  projects/go-lib/src/lib/components/go-table/go-table.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-column-docs/table-column-docs.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-column-docs/table-column-docs.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-overview/table-overview.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/table-docs/components/table-overview/table-overview.component.ts
Labels: feature

#824 [Chore] Panel Disable Option
  projects/go-lib/src/lib/components/go-action-sheet/go-panel/go-panel.component.html
  projects/go-lib/src/lib/components/go-action-sheet/go-panel/go-panel.component.scss
  projects/go-lib/src/lib/components/go-action-sheet/go-panel/go-panel.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/action-sheet-docs/components/action-sheet-panel-docs/action-sheet-panel-docs.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/action-sheet-docs/components/action-sheet-panel-docs/action-sheet-panel-docs.component.ts
Labels: chore

#835 [Bug] go-select Clear On Add
  projects/go-lib/src/lib/components/go-select/go-select.component.html
  projects/go-lib/src/lib/components/go-select/go-select.component.ts
Labels: bug
