Repository mobi/goponents, pull requests merged in 2023-03, with the labels that each got.

#887 [Chore] Reduce spacing under header within cards #786
  projects/go-lib/src/lib/components/go-card/go-card.component.scss
Labels: chore, UX Review

#892 [Feature] Progress Bar
  projects/go-lib/src/lib/components/go-badge/go-badge.component.spec.ts
  projects/go-lib/src/lib/components/go-progress-bar/go-progress-bar.component.html
  projects/go-lib/src/lib/components/go-progress-bar/go-progress-bar.component.scss
  projects/go-lib/src/lib/components/go-progress-bar/go-progress-bar.component.spec.ts
  projects/go-lib/src/lib/components/go-progress-bar/go-progress-bar.component.ts
  projects/go-lib/src/lib/components/go-progress-bar/go-progress-bar.module.ts
  projects/go-lib/src/lib/go-shared.module.ts
  projects/go-lib/src/public_api.ts
  projects/go-style-guide/src/app/app.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/progress-bar-docs/progress-bar-docs.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/progress-bar-docs/progress-bar-docs.component.ts
  projects/go-style-guide/src/app/features/ui-kit/routes/ui-kit-routing.module.ts
  projects/go-style-guide/src/app/features/ui-kit/ui-kit.module.ts
Labels: feature

#890 Changes [CHORE] 868 max height for toast
  projects/go-lib/src/lib/components/go-toast/go-toast.component.html
  projects/go-lib/src/lib/components/go-toast/go-toast.component.ts
  projects/go-style-guide/src/app/features/ui-kit/components/toast-docs/toast-docs.component.html
  projects/go-style-guide/src/app/features/ui-kit/components/toast-docs/toast-docs.component.ts
Labels: chore, UX Review

#883 Changes_for_bugfix-872_chore-869-870_task
  projects/go-lib/src/lib/components/go-button/go-button.component.scss
  projects/go-lib/src/lib/components/go-hint/go-hint.component.scss
  projects/go-lib/styles/_hints.scss
Labels: bug, chore, UX Review
